services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pg
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=adm@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
    ports:
      - "8080:80"