from sqlalchemy import delete, select
from sqlalchemy.orm import Session
from diary.models import baseprod

baseprods = (
    {"name": "Молоко 3.2%", "product_type": "dairy", "calories": 60, "fats": 3.2, "proteins": 3.0, "carbs": 4.7},
    {"name": "Куриная грудка", "product_type": "meatfish", "calories": 165, "fats": 3.6, "proteins": 31.0, "carbs": 0},
    {"name": "Гречка", "product_type": "grains", "calories": 343, "fats": 3.4, "proteins": 13.6, "carbs": 71.5},
    {"name": "Яблоко", "product_type": "fruits", "calories": 52, "fats": 0.2, "proteins": 0.3, "carbs": 13.8},
    {"name": "Огурец", "product_type": "vegetables", "calories": 15, "fats": 0.1, "proteins": 0.7, "carbs": 3.6},
    {"name": "Вода", "product_type": "beverages", "calories": 0, "fats": 0, "proteins": 0, "carbs": 0},
    {"name": "Индейка", "product_type": "meatfish", "calories": 135, "fats": 2.0, "proteins": 29.0, "carbs": 0},
    {"name": "Говядина", "product_type": "meatfish", "calories": 187, "fats": 12.0, "proteins": 19.0, "carbs": 0},
    {"name": "Свинина", "product_type": "meatfish", "calories": 242, "fats": 16.0, "proteins": 27.0, "carbs": 0},
    {"name": "Лосось", "product_type": "meatfish", "calories": 208, "fats": 13.0, "proteins": 20.0, "carbs": 0},
    {"name": "Тунец", "product_type": "meatfish", "calories": 132, "fats": 1.0, "proteins": 29.0, "carbs": 0},
    {"name": "Треска", "product_type": "meatfish", "calories": 82, "fats": 0.7, "proteins": 18.0, "carbs": 0},
    {"name": "Креветки", "product_type": "meatfish", "calories": 99, "fats": 0.3, "proteins": 24.0, "carbs": 0.2},
    {"name": "Яйцо куриное", "product_type": "meatfish", "calories": 157, "fats": 11.0, "proteins": 13.0, "carbs": 1.1},
    {"name": "Творог 5%", "product_type": "dairy", "calories": 121, "fats": 5.0, "proteins": 17.0, "carbs": 1.8},
    {"name": "Йогурт натуральный", "product_type": "dairy", "calories": 60, "fats": 3.2, "proteins": 5.0, "carbs": 4.0},
    {"name": "Кефир 2.5%", "product_type": "dairy", "calories": 53, "fats": 2.5, "proteins": 3.0, "carbs": 4.0},
    {"name": "Сметана 15%", "product_type": "dairy", "calories": 158, "fats": 15.0, "proteins": 2.6, "carbs": 3.6},
    {"name": "Рис вареный", "product_type": "grains", "calories": 130, "fats": 0.3, "proteins": 2.7, "carbs": 28.0},
    {"name": "Овсянка", "product_type": "grains", "calories": 366, "fats": 6.9, "proteins": 11.9, "carbs": 65.4},
    {"name": "Перловка", "product_type": "grains", "calories": 320, "fats": 1.1, "proteins": 9.3, "carbs": 73.7},
    {"name": "Пшено", "product_type": "grains", "calories": 342, "fats": 3.5, "proteins": 11.5, "carbs": 69.3},
    {"name": "Хлеб ржаной", "product_type": "grains", "calories": 210, "fats": 1.2, "proteins": 6.6, "carbs": 40.7},
    {"name": "Хлеб пшеничный", "product_type": "grains", "calories": 265, "fats": 3.2, "proteins": 9.0, "carbs": 49.0},
    {"name": "Картофель", "product_type": "vegetables", "calories": 77, "fats": 0.1, "proteins": 2.0, "carbs": 17.5},
    {"name": "Морковь", "product_type": "vegetables", "calories": 35, "fats": 0.2, "proteins": 1.3, "carbs": 6.9},
    {"name": "Помидор", "product_type": "vegetables", "calories": 18, "fats": 0.2, "proteins": 0.9, "carbs": 3.9},
    {"name": "Болгарский перец", "product_type": "vegetables", "calories": 27, "fats": 0.1, "proteins": 1.0, "carbs": 5.3},
    {"name": "Капуста белокочанная", "product_type": "vegetables", "calories": 27, "fats": 0.1, "proteins": 1.8, "carbs": 4.7},
    {"name": "Брокколи", "product_type": "vegetables", "calories": 34, "fats": 0.4, "proteins": 2.8, "carbs": 6.6},
    {"name": "Цветная капуста", "product_type": "vegetables", "calories": 25, "fats": 0.3, "proteins": 1.9, "carbs": 5.0},
    {"name": "Кабачок", "product_type": "vegetables", "calories": 24, "fats": 0.3, "proteins": 0.6, "carbs": 4.6},
    {"name": "Баклажан", "product_type": "vegetables", "calories": 24, "fats": 0.1, "proteins": 1.0, "carbs": 5.0},
    {"name": "Свекла", "product_type": "vegetables", "calories": 43, "fats": 0.2, "proteins": 1.6, "carbs": 9.6},
    {"name": "Лук репчатый", "product_type": "vegetables", "calories": 41, "fats": 0.2, "proteins": 1.4, "carbs": 9.0},
    {"name": "Чеснок", "product_type": "vegetables", "calories": 149, "fats": 0.5, "proteins": 6.4, "carbs": 33.1},
    {"name": "Шпинат", "product_type": "vegetables", "calories": 23, "fats": 0.4, "proteins": 2.9, "carbs": 3.6},
    {"name": "Салат листовой", "product_type": "vegetables", "calories": 15, "fats": 0.2, "proteins": 1.4, "carbs": 2.9},
    {"name": "Авокадо", "product_type": "fruits", "calories": 160, "fats": 14.7, "proteins": 2.0, "carbs": 8.5},
    {"name": "Банан", "product_type": "fruits", "calories": 89, "fats": 0.3, "proteins": 1.1, "carbs": 22.8},
    {"name": "Апельсин", "product_type": "fruits", "calories": 47, "fats": 0.1, "proteins": 0.9, "carbs": 11.8},
    {"name": "Груша", "product_type": "fruits", "calories": 57, "fats": 0.1, "proteins": 0.4, "carbs": 15.2},
    {"name": "Виноград", "product_type": "fruits", "calories": 69, "fats": 0.2, "proteins": 0.7, "carbs": 18.1},
    {"name": "Арбуз", "product_type": "fruits", "calories": 30, "fats": 0.2, "proteins": 0.6, "carbs": 7.6},
    {"name": "Дыня", "product_type": "fruits", "calories": 34, "fats": 0.2, "proteins": 0.8, "carbs": 8.2},
    {"name": "Киви", "product_type": "fruits", "calories": 61, "fats": 0.5, "proteins": 1.1, "carbs": 14.7},
    {"name": "Персик", "product_type": "fruits", "calories": 39, "fats": 0.3, "proteins": 0.9, "carbs": 9.5},
    {"name": "Слива", "product_type": "fruits", "calories": 46, "fats": 0.3, "proteins": 0.7, "carbs": 11.4},
    {"name": "Клубника", "product_type": "fruits", "calories": 32, "fats": 0.3, "proteins": 0.7, "carbs": 7.7},
    {"name": "Малина", "product_type": "fruits", "calories": 52, "fats": 0.7, "proteins": 1.2, "carbs": 11.9},
    {"name": "Голубика", "product_type": "fruits", "calories": 57, "fats": 0.3, "proteins": 0.7, "carbs": 14.5},
    {"name": "Миндаль", "product_type": "other", "calories": 579, "fats": 49.9, "proteins": 21.2, "carbs": 21.6},
    {"name": "Грецкий орех", "product_type": "other", "calories": 654, "fats": 65.2, "proteins": 15.2, "carbs": 13.7},
    {"name": "Арахис", "product_type": "other", "calories": 567, "fats": 49.2, "proteins": 25.8, "carbs": 16.1},
    {"name": "Семена подсолнечника", "product_type": "other", "calories": 584, "fats": 51.5, "proteins": 20.8, "carbs": 20.0},
    {"name": "Оливковое масло", "product_type": "other", "calories": 884, "fats": 100.0, "proteins": 0, "carbs": 0},
    {"name": "Мёд", "product_type": "other", "calories": 304, "fats": 0, "proteins": 0.3, "carbs": 82.4},
    {"name": "Чай черный без сахара", "product_type": "beverages", "calories": 1, "fats": 0, "proteins": 0, "carbs": 0.3},
    {"name": "Компот", "product_type": "beverages", "calories": 45, "fats": 0, "proteins": 0.2, "carbs": 11.0},
    {"name": "Молоко 0.5%", "product_type": "dairy", "calories": 35, "fats": 0.5, "proteins": 3.0, "carbs": 4.8},
    {"name": "Молоко 1.5%", "product_type": "dairy", "calories": 44, "fats": 1.5, "proteins": 3.0, "carbs": 4.8},
    {"name": "Молоко 2.5%", "product_type": "dairy", "calories": 52, "fats": 2.5, "proteins": 3.0, "carbs": 4.7},
    {"name": "Молоко 6%", "product_type": "dairy", "calories": 83, "fats": 6.0, "proteins": 3.0, "carbs": 4.7},
    {"name": "Кефир 0.1%", "product_type": "dairy", "calories": 30, "fats": 0.1, "proteins": 3.0, "carbs": 4.0},
    {"name": "Кефир 1%", "product_type": "dairy", "calories": 40, "fats": 1.0, "proteins": 3.0, "carbs": 4.0},
    {"name": "Кефир 3.2%", "product_type": "dairy", "calories": 59, "fats": 3.2, "proteins": 2.9, "carbs": 4.0},
    {"name": "Ряженка 2.5%", "product_type": "dairy", "calories": 54, "fats": 2.5, "proteins": 2.9, "carbs": 4.2},
    {"name": "Ряженка 4%", "product_type": "dairy", "calories": 67, "fats": 4.0, "proteins": 2.8, "carbs": 4.2},
    {"name": "Йогурт 0.1%", "product_type": "dairy", "calories": 40, "fats": 0.1, "proteins": 4.0, "carbs": 5.0},
    {"name": "Йогурт 1.5%", "product_type": "dairy", "calories": 52, "fats": 1.5, "proteins": 4.0, "carbs": 5.0},
    {"name": "Творог 0%", "product_type": "dairy", "calories": 71, "fats": 0.0, "proteins": 16.5, "carbs": 1.3},
    {"name": "Творог 2%", "product_type": "dairy", "calories": 103, "fats": 2.0, "proteins": 18.0, "carbs": 2.0},
    {"name": "Сметана 10%", "product_type": "dairy", "calories": 115, "fats": 10.0, "proteins": 3.0, "carbs": 3.9},
    {"name": "Сметана 20%", "product_type": "dairy", "calories": 206, "fats": 20.0, "proteins": 2.8, "carbs": 3.2},
    {"name": "Сливки 10%", "product_type": "dairy", "calories": 118, "fats": 10.0, "proteins": 3.0, "carbs": 4.0},
    {"name": "Сливки 20%", "product_type": "dairy", "calories": 206, "fats": 20.0, "proteins": 2.5, "carbs": 3.5},
    {"name": "Моцарелла", "product_type": "dairy", "calories": 280, "fats": 18.0, "proteins": 28.0, "carbs": 3.0},
    {"name": "Брынза", "product_type": "dairy", "calories": 260, "fats": 20.0, "proteins": 17.0, "carbs": 0.5},
    {"name": "Пармезан", "product_type": "dairy", "calories": 392, "fats": 30.0, "proteins": 35.8, "carbs": 3.2},
    {"name": "Куриное бедро без кожи", "product_type": "meatfish", "calories": 135, "fats": 5.0, "proteins": 21.0, "carbs": 0},
    {"name": "Индюшиное бедро", "product_type": "meatfish", "calories": 144, "fats": 5.0, "proteins": 21.0, "carbs": 0},
    {"name": "Утка без кожи", "product_type": "meatfish", "calories": 140, "fats": 5.0, "proteins": 19.0, "carbs": 0},
    {"name": "Лосось слабосоленый", "product_type": "meatfish", "calories": 202, "fats": 12.5, "proteins": 22.0, "carbs": 0},
    {"name": "Форель", "product_type": "meatfish", "calories": 148, "fats": 6.5, "proteins": 20.5, "carbs": 0},
    {"name": "Сельдь", "product_type": "meatfish", "calories": 158, "fats": 9.0, "proteins": 17.7, "carbs": 0},
    {"name": "Скумбрия", "product_type": "meatfish", "calories": 205, "fats": 13.9, "proteins": 18.6, "carbs": 0},
    {"name": "Минтай", "product_type": "meatfish", "calories": 72, "fats": 0.9, "proteins": 15.9, "carbs": 0},
    {"name": "Щука", "product_type": "meatfish", "calories": 84, "fats": 1.1, "proteins": 18.4, "carbs": 0},
    {"name": "Кальмар", "product_type": "meatfish", "calories": 92, "fats": 1.4, "proteins": 18.0, "carbs": 2.0},
    {"name": "Мидии", "product_type": "meatfish", "calories": 86, "fats": 2.2, "proteins": 11.9, "carbs": 3.7},
    {"name": "Печень трески", "product_type": "meatfish", "calories": 613, "fats": 65.7, "proteins": 4.2, "carbs": 1.2},
    {"name": "Гречка вареная", "product_type": "grains", "calories": 110, "fats": 1.0, "proteins": 4.2, "carbs": 21.3},
    {"name": "Рис сухой", "product_type": "grains", "calories": 344, "fats": 0.7, "proteins": 6.7, "carbs": 78.9},
    {"name": "Булгур", "product_type": "grains", "calories": 342, "fats": 1.3, "proteins": 12.3, "carbs": 75.9},
    {"name": "Кускус", "product_type": "grains", "calories": 376, "fats": 0.6, "proteins": 12.8, "carbs": 77.4},
    {"name": "Киноа", "product_type": "grains", "calories": 368, "fats": 6.1, "proteins": 14.1, "carbs": 64.2},
    {"name": "Кукурузная крупа", "product_type": "grains", "calories": 328, "fats": 1.2, "proteins": 8.3, "carbs": 71.0},
    {"name": "Ячневая крупа", "product_type": "grains", "calories": 324, "fats": 1.3, "proteins": 10.0, "carbs": 71.7},
    {"name": "Хлеб цельнозерновой", "product_type": "grains", "calories": 247, "fats": 3.4, "proteins": 13.0, "carbs": 41.0},
    {"name": "Лаваш", "product_type": "grains", "calories": 275, "fats": 1.2, "proteins": 9.1, "carbs": 56.0},
    {"name": "Хлебцы ржаные", "product_type": "grains", "calories": 310, "fats": 2.3, "proteins": 10.0, "carbs": 63.0},
    {"name": "Отруби овсяные", "product_type": "grains", "calories": 246, "fats": 7.0, "proteins": 17.3, "carbs": 66.2},
    {"name": "Кукуруза консервированная", "product_type": "vegetables", "calories": 70, "fats": 1.2, "proteins": 3.2, "carbs": 22.0},
    {"name": "Горошек консервированный", "product_type": "vegetables", "calories": 55, "fats": 0.2, "proteins": 3.6, "carbs": 9.8},
    {"name": "Фасоль красная вареная", "product_type": "vegetables", "calories": 127, "fats": 0.5, "proteins": 8.7, "carbs": 22.8},
    {"name": "Чечевица вареная", "product_type": "vegetables", "calories": 116, "fats": 0.4, "proteins": 9.0, "carbs": 20.1},
    {"name": "Нут вареный", "product_type": "vegetables", "calories": 164, "fats": 2.6, "proteins": 8.9, "carbs": 27.4},
    {"name": "Тыква", "product_type": "vegetables", "calories": 26, "fats": 0.1, "proteins": 1.0, "carbs": 6.5},
    {"name": "Стручковая фасоль", "product_type": "vegetables", "calories": 31, "fats": 0.2, "proteins": 1.8, "carbs": 7.0},
    {"name": "Редис", "product_type": "vegetables", "calories": 16, "fats": 0.1, "proteins": 0.7, "carbs": 3.4},
    {"name": "Дайкон", "product_type": "vegetables", "calories": 18, "fats": 0.1, "proteins": 0.6, "carbs": 4.1},
    {"name": "Манго", "product_type": "fruits", "calories": 60, "fats": 0.4, "proteins": 0.8, "carbs": 15.0},
    {"name": "Ананас", "product_type": "fruits", "calories": 50, "fats": 0.1, "proteins": 0.5, "carbs": 13.1},
    {"name": "Гранат", "product_type": "fruits", "calories": 83, "fats": 1.2, "proteins": 1.7, "carbs": 18.7},
    {"name": "Черешня", "product_type": "fruits", "calories": 63, "fats": 0.2, "proteins": 1.1, "carbs": 16.0},
    {"name": "Смородина черная", "product_type": "fruits", "calories": 44, "fats": 0.4, "proteins": 1.0, "carbs": 7.3},
    {"name": "Курага", "product_type": "fruits", "calories": 241, "fats": 0.5, "proteins": 3.4, "carbs": 62.6},
    {"name": "Изюм", "product_type": "fruits", "calories": 299, "fats": 0.5, "proteins": 3.1, "carbs": 79.2},
    {"name": "Чернослив", "product_type": "fruits", "calories": 240, "fats": 0.4, "proteins": 2.2, "carbs": 63.9},
    {"name": "Фундук", "product_type": "other", "calories": 628, "fats": 60.8, "proteins": 15.0, "carbs": 16.7},
    {"name": "Кешью", "product_type": "other", "calories": 553, "fats": 43.9, "proteins": 18.2, "carbs": 30.2},
    {"name": "Фисташки", "product_type": "other", "calories": 562, "fats": 45.3, "proteins": 20.2, "carbs": 27.2},
    {"name": "Кунжут", "product_type": "other", "calories": 573, "fats": 49.7, "proteins": 17.7, "carbs": 23.4},
    {"name": "Семена льна", "product_type": "other", "calories": 534, "fats": 42.2, "proteins": 18.3, "carbs": 28.9},
    {"name": "Семена чиа", "product_type": "other", "calories": 486, "fats": 30.7, "proteins": 16.5, "carbs": 42.1},
    {"name": "Зеленый чай без сахара", "product_type": "beverages", "calories": 1, "fats": 0, "proteins": 0, "carbs": 0.2},
    {"name": "Минеральная вода", "product_type": "beverages", "calories": 0, "fats": 0, "proteins": 0, "carbs": 0},
    {"name": "Какао-порошок", "product_type": "beverages", "calories": 228, "fats": 13.1, "proteins": 19.6, "carbs": 57.9},
    {"name": "Баранина", "product_type": "meatfish", "calories": 294, "fats": 21.0, "proteins": 25.0, "carbs": 0},
    {"name": "Телятина", "product_type": "meatfish", "calories": 131, "fats": 2.0, "proteins": 26.0, "carbs": 0},
    {"name": "Кролик", "product_type": "meatfish", "calories": 173, "fats": 8.0, "proteins": 33.0, "carbs": 0},
    {"name": "Гусь", "product_type": "meatfish", "calories": 305, "fats": 21.8, "proteins": 22.7, "carbs": 0},
    {"name": "Перепелка", "product_type": "meatfish", "calories": 227, "fats": 14.1, "proteins": 25.0, "carbs": 0},
    {"name": "Печень говяжья", "product_type": "meatfish", "calories": 135, "fats": 3.6, "proteins": 20.4, "carbs": 5.9},
    {"name": "Печень куриная", "product_type": "meatfish", "calories": 119, "fats": 4.8, "proteins": 16.9, "carbs": 0.7},
    {"name": "Сердце говяжье", "product_type": "meatfish", "calories": 112, "fats": 3.2, "proteins": 17.7, "carbs": 3.1},
    {"name": "Сердце куриное", "product_type": "meatfish", "calories": 153, "fats": 9.3, "proteins": 15.6, "carbs": 0.8},
    {"name": "Желудки куриные", "product_type": "meatfish", "calories": 94, "fats": 2.1, "proteins": 17.7, "carbs": 0},
    {"name": "Язык говяжий", "product_type": "meatfish", "calories": 224, "fats": 16.1, "proteins": 16.0, "carbs": 3.6},
    {"name": "Сосиски молочные", "product_type": "meatfish", "calories": 266, "fats": 23.9, "proteins": 11.0, "carbs": 1.6},
    {"name": "Сардельки говяжьи", "product_type": "meatfish", "calories": 232, "fats": 19.3, "proteins": 13.1, "carbs": 1.5},
    {"name": "Колбаса вареная Докторская", "product_type": "meatfish", "calories": 257, "fats": 22.2, "proteins": 12.8, "carbs": 1.5},
    {"name": "Колбаса сырокопченая", "product_type": "meatfish", "calories": 473, "fats": 41.5, "proteins": 24.8, "carbs": 0},
    {"name": "Ветчина из индейки", "product_type": "meatfish", "calories": 112, "fats": 3.5, "proteins": 18.0, "carbs": 2.0},
    {"name": "Грудинка свиная", "product_type": "meatfish", "calories": 518, "fats": 53.0, "proteins": 10.1, "carbs": 0},
    {"name": "Бекон", "product_type": "meatfish", "calories": 541, "fats": 42.0, "proteins": 37.0, "carbs": 0},
    {"name": "Карп", "product_type": "meatfish", "calories": 112, "fats": 5.3, "proteins": 16.0, "carbs": 0},
    {"name": "Судак", "product_type": "meatfish", "calories": 83, "fats": 1.1, "proteins": 18.4, "carbs": 0},
    {"name": "Окунь морской", "product_type": "meatfish", "calories": 79, "fats": 1.5, "proteins": 15.3, "carbs": 0},
    {"name": "Камбала", "product_type": "meatfish", "calories": 90, "fats": 1.2, "proteins": 18.8, "carbs": 0},
    {"name": "Хек", "product_type": "meatfish", "calories": 86, "fats": 2.2, "proteins": 16.6, "carbs": 0},
    {"name": "Пангасиус", "product_type": "meatfish", "calories": 89, "fats": 3.0, "proteins": 15.0, "carbs": 0},
    {"name": "Тилапия", "product_type": "meatfish", "calories": 96, "fats": 1.7, "proteins": 20.1, "carbs": 0},
    {"name": "Горбуша", "product_type": "meatfish", "calories": 142, "fats": 6.0, "proteins": 20.5, "carbs": 0},
    {"name": "Кета", "product_type": "meatfish", "calories": 138, "fats": 5.6, "proteins": 19.0, "carbs": 0},
    {"name": "Семга", "product_type": "meatfish", "calories": 208, "fats": 13.0, "proteins": 20.0, "carbs": 0},
    {"name": "Икра красная (горбуши)", "product_type": "meatfish", "calories": 249, "fats": 13.2, "proteins": 31.6, "carbs": 1.0},
    {"name": "Икра черная", "product_type": "meatfish", "calories": 235, "fats": 11.3, "proteins": 26.8, "carbs": 0},
    {"name": "Осьминог", "product_type": "meatfish", "calories": 82, "fats": 1.0, "proteins": 14.9, "carbs": 2.2},
    {"name": "Каракатица", "product_type": "meatfish", "calories": 79, "fats": 0.7, "proteins": 16.2, "carbs": 0.8},
    {"name": "Краб", "product_type": "meatfish", "calories": 97, "fats": 1.5, "proteins": 19.0, "carbs": 0},
    {"name": "Устрицы", "product_type": "meatfish", "calories": 68, "fats": 2.5, "proteins": 7.0, "carbs": 3.9},
    {"name": "Морской гребешок", "product_type": "meatfish", "calories": 88, "fats": 0.8, "proteins": 17.5, "carbs": 0},
    {"name": "Яйцо перепелиное", "product_type": "meatfish", "calories": 168, "fats": 13.1, "proteins": 11.9, "carbs": 0.6},
    {"name": "Яйцо утиное", "product_type": "meatfish", "calories": 185, "fats": 13.8, "proteins": 12.8, "carbs": 1.5},
    {"name": "Сыр Российский", "product_type": "dairy", "calories": 363, "fats": 29.5, "proteins": 24.1, "carbs": 0.3},
    {"name": "Сыр Голландский", "product_type": "dairy", "calories": 352, "fats": 26.8, "proteins": 26.0, "carbs": 0},
    {"name": "Сыр Гауда", "product_type": "dairy", "calories": 356, "fats": 27.4, "proteins": 24.9, "carbs": 2.2},
    {"name": "Сыр Маасдам", "product_type": "dairy", "calories": 350, "fats": 27.5, "proteins": 23.5, "carbs": 0},
    {"name": "Сыр Чеддер", "product_type": "dairy", "calories": 402, "fats": 33.1, "proteins": 24.9, "carbs": 1.3},
    {"name": "Сыр Фета", "product_type": "dairy", "calories": 264, "fats": 21.3, "proteins": 14.2, "carbs": 4.1},
    {"name": "Сыр Рикотта", "product_type": "dairy", "calories": 174, "fats": 13.0, "proteins": 11.3, "carbs": 3.0},
    {"name": "Сыр Маскарпоне", "product_type": "dairy", "calories": 412, "fats": 41.5, "proteins": 4.8, "carbs": 4.8},
    {"name": "Сыр Сулугуни", "product_type": "dairy", "calories": 286, "fats": 22.0, "proteins": 20.5, "carbs": 0},
    {"name": "Сыр Адыгейский", "product_type": "dairy", "calories": 240, "fats": 14.0, "proteins": 19.0, "carbs": 1.5},
    {"name": "Сыр Дор Блю", "product_type": "dairy", "calories": 354, "fats": 30.0, "proteins": 21.0, "carbs": 0},
    {"name": "Снежок", "product_type": "dairy", "calories": 79, "fats": 2.5, "proteins": 2.7, "carbs": 10.8},
    {"name": "Айран", "product_type": "dairy", "calories": 24, "fats": 1.0, "proteins": 1.1, "carbs": 1.4},
    {"name": "Тан", "product_type": "dairy", "calories": 24, "fats": 1.0, "proteins": 1.1, "carbs": 1.4},
    {"name": "Кумыс", "product_type": "dairy", "calories": 50, "fats": 1.0, "proteins": 2.1, "carbs": 5.0},
    {"name": "Масло сливочное 72.5%", "product_type": "dairy", "calories": 661, "fats": 72.5, "proteins": 0.8, "carbs": 1.3},
    {"name": "Масло сливочное 82.5%", "product_type": "dairy", "calories": 748, "fats": 82.5, "proteins": 0.5, "carbs": 0.8},
    {"name": "Маргарин", "product_type": "dairy", "calories": 717, "fats": 82.0, "proteins": 0.3, "carbs": 1.0},
    {"name": "Сырки творожные глазированные", "product_type": "dairy", "calories": 407, "fats": 27.7, "proteins": 7.9, "carbs": 31.8},
    {"name": "Макароны твердых сортов (сухие)", "product_type": "grains", "calories": 350, "fats": 1.5, "proteins": 12.0, "carbs": 71.0},
    {"name": "Спагетти вареные", "product_type": "grains", "calories": 158, "fats": 0.9, "proteins": 5.8, "carbs": 30.9},
    {"name": "Лапша яичная", "product_type": "grains", "calories": 384, "fats": 4.4, "proteins": 14.2, "carbs": 71.3},
    {"name": "Лапша гречневая (соба)", "product_type": "grains", "calories": 336, "fats": 0.7, "proteins": 14.4, "carbs": 70.5},
    {"name": "Лапша рисовая", "product_type": "grains", "calories": 364, "fats": 0.6, "proteins": 3.4, "carbs": 80.0},
    {"name": "Лапша фунчоза", "product_type": "grains", "calories": 320, "fats": 0.5, "proteins": 0.7, "carbs": 84.0},
    {"name": "Манная крупа", "product_type": "grains", "calories": 328, "fats": 1.0, "proteins": 10.3, "carbs": 73.3},
    {"name": "Полба", "product_type": "grains", "calories": 338, "fats": 2.4, "proteins": 14.6, "carbs": 70.2},
    {"name": "Амарант", "product_type": "grains", "calories": 371, "fats": 7.0, "proteins": 13.6, "carbs": 65.2},
    {"name": "Хлопья кукурузные", "product_type": "grains", "calories": 363, "fats": 1.0, "proteins": 6.9, "carbs": 83.8},
    {"name": "Хлеб бородинский", "product_type": "grains", "calories": 208, "fats": 1.2, "proteins": 6.8, "carbs": 39.8},
    {"name": "Батон нарезной", "product_type": "grains", "calories": 264, "fats": 2.9, "proteins": 7.5, "carbs": 51.4},
    {"name": "Капуста краснокочанная", "product_type": "vegetables", "calories": 26, "fats": 0.2, "proteins": 1.5, "carbs": 5.1},
    {"name": "Капуста пекинская", "product_type": "vegetables", "calories": 16, "fats": 0.2, "proteins": 1.2, "carbs": 2.0},
    {"name": "Капуста брюссельская", "product_type": "vegetables", "calories": 43, "fats": 0.3, "proteins": 4.8, "carbs": 5.9},
    {"name": "Кольраби", "product_type": "vegetables", "calories": 42, "fats": 0.1, "proteins": 2.8, "carbs": 7.4},
    {"name": "Лук порей", "product_type": "vegetables", "calories": 33, "fats": 0.2, "proteins": 2.0, "carbs": 6.3},
    {"name": "Лук зеленый", "product_type": "vegetables", "calories": 19, "fats": 0.1, "proteins": 1.3, "carbs": 3.2},
    {"name": "Петрушка", "product_type": "vegetables", "calories": 47, "fats": 0.4, "proteins": 3.7, "carbs": 7.6},
    {"name": "Укроп", "product_type": "vegetables", "calories": 40, "fats": 0.5, "proteins": 2.5, "carbs": 6.3},
    {"name": "Кинза", "product_type": "vegetables", "calories": 23, "fats": 0.5, "proteins": 2.1, "carbs": 1.9},
    {"name": "Базилик", "product_type": "vegetables", "calories": 23, "fats": 0.6, "proteins": 3.2, "carbs": 2.7},
    {"name": "Руккола", "product_type": "vegetables", "calories": 25, "fats": 0.7, "proteins": 2.6, "carbs": 2.1},
    {"name": "Сельдерей (стебель)", "product_type": "vegetables", "calories": 14, "fats": 0.1, "proteins": 0.9, "carbs": 2.1},
    {"name": "Сельдерей (корень)", "product_type": "vegetables", "calories": 32, "fats": 0.3, "proteins": 1.3, "carbs": 6.5},
    {"name": "Спаржа", "product_type": "vegetables", "calories": 20, "fats": 0.1, "proteins": 1.9, "carbs": 3.1},
    {"name": "Репа", "product_type": "vegetables", "calories": 30, "fats": 0.1, "proteins": 1.5, "carbs": 5.9},
    {"name": "Пастернак", "product_type": "vegetables", "calories": 75, "fats": 0.3, "proteins": 1.2, "carbs": 18.0},
    {"name": "Топинамбур", "product_type": "vegetables", "calories": 61, "fats": 0.1, "proteins": 2.1, "carbs": 12.8},
    {"name": "Батат", "product_type": "vegetables", "calories": 86, "fats": 0.1, "proteins": 1.6, "carbs": 20.1},
    {"name": "Оливки консервированные", "product_type": "vegetables", "calories": 115, "fats": 10.7, "proteins": 0.8, "carbs": 6.3},
    {"name": "Маслины консервированные", "product_type": "vegetables", "calories": 115, "fats": 10.7, "proteins": 0.8, "carbs": 6.3},
    {"name": "Горох колотый сухой", "product_type": "vegetables", "calories": 298, "fats": 2.0, "proteins": 20.5, "carbs": 49.5},
    {"name": "Фасоль стручковая замороженная", "product_type": "vegetables", "calories": 24, "fats": 0.1, "proteins": 1.2, "carbs": 4.5},
    {"name": "Томатная паста", "product_type": "vegetables", "calories": 82, "fats": 0.5, "proteins": 4.3, "carbs": 19.0},
    {"name": "Шампиньоны свежие", "product_type": "vegetables", "calories": 27, "fats": 1.0, "proteins": 4.3, "carbs": 1.0},
    {"name": "Вешенки", "product_type": "vegetables", "calories": 38, "fats": 0.4, "proteins": 3.3, "carbs": 3.8},
    {"name": "Белый гриб", "product_type": "vegetables", "calories": 34, "fats": 1.7, "proteins": 3.7, "carbs": 1.1},
    {"name": "Опята", "product_type": "vegetables", "calories": 22, "fats": 1.2, "proteins": 2.2, "carbs": 0.5},
    {"name": "Лисички", "product_type": "vegetables", "calories": 19, "fats": 1.0, "proteins": 1.5, "carbs": 1.0},
    {"name": "Шиитаке", "product_type": "vegetables", "calories": 34, "fats": 0.5, "proteins": 2.2, "carbs": 6.8},
    {"name": "Морская капуста", "product_type": "vegetables", "calories": 24, "fats": 0.2, "proteins": 0.9, "carbs": 3.0},
    {"name": "Грейпфрут", "product_type": "fruits", "calories": 35, "fats": 0.2, "proteins": 0.7, "carbs": 6.5},
    {"name": "Мандарин", "product_type": "fruits", "calories": 38, "fats": 0.2, "proteins": 0.8, "carbs": 7.5},
    {"name": "Лимон", "product_type": "fruits", "calories": 29, "fats": 0.3, "proteins": 1.1, "carbs": 9.3},
    {"name": "Лайм", "product_type": "fruits", "calories": 30, "fats": 0.2, "proteins": 0.7, "carbs": 10.5},
    {"name": "Помело", "product_type": "fruits", "calories": 38, "fats": 0.0, "proteins": 0.8, "carbs": 8.6},
    {"name": "Нектарин", "product_type": "fruits", "calories": 44, "fats": 0.3, "proteins": 1.1, "carbs": 10.5},
    {"name": "Абрикос", "product_type": "fruits", "calories": 44, "fats": 0.1, "proteins": 0.9, "carbs": 9.0},
    {"name": "Хурма", "product_type": "fruits", "calories": 67, "fats": 0.4, "proteins": 0.5, "carbs": 15.3},
    {"name": "Инжир свежий", "product_type": "fruits", "calories": 74, "fats": 0.3, "proteins": 0.8, "carbs": 19.2},
    {"name": "Папайя", "product_type": "fruits", "calories": 43, "fats": 0.3, "proteins": 0.5, "carbs": 10.8},
    {"name": "Маракуйя", "product_type": "fruits", "calories": 97, "fats": 0.7, "proteins": 2.2, "carbs": 23.4},
    {"name": "Личи", "product_type": "fruits", "calories": 66, "fats": 0.4, "proteins": 0.8, "carbs": 16.5},
    {"name": "Ежевика", "product_type": "fruits", "calories": 43, "fats": 0.5, "proteins": 1.4, "carbs": 9.6},
    {"name": "Черника", "product_type": "fruits", "calories": 44, "fats": 0.3, "proteins": 1.1, "carbs": 7.6},
    {"name": "Клюква", "product_type": "fruits", "calories": 26, "fats": 0.2, "proteins": 0.5, "carbs": 3.7},
    {"name": "Брусника", "product_type": "fruits", "calories": 43, "fats": 0.5, "proteins": 0.7, "carbs": 8.2},
    {"name": "Облепиха", "product_type": "fruits", "calories": 82, "fats": 5.4, "proteins": 1.2, "carbs": 5.7},
    {"name": "Крыжовник", "product_type": "fruits", "calories": 43, "fats": 0.2, "proteins": 0.7, "carbs": 9.1},
    {"name": "Смородина красная", "product_type": "fruits", "calories": 43, "fats": 0.2, "proteins": 0.6, "carbs": 7.7},
    {"name": "Вишня", "product_type": "fruits", "calories": 52, "fats": 0.2, "proteins": 0.8, "carbs": 10.6},
    {"name": "Земляника", "product_type": "fruits", "calories": 41, "fats": 0.4, "proteins": 0.8, "carbs": 7.5},
    {"name": "Инжир сушеный", "product_type": "fruits", "calories": 257, "fats": 0.8, "proteins": 3.1, "carbs": 57.9},
    {"name": "Финики", "product_type": "fruits", "calories": 292, "fats": 0.5, "proteins": 2.5, "carbs": 69.2},
    {"name": "Яблоки сушеные", "product_type": "fruits", "calories": 231, "fats": 0.1, "proteins": 2.2, "carbs": 59.0},
    {"name": "Цукаты", "product_type": "fruits", "calories": 322, "fats": 0.0, "proteins": 0.0, "carbs": 80.5},
    {"name": "Макадамия", "product_type": "other", "calories": 718, "fats": 75.8, "proteins": 7.9, "carbs": 13.8},
    {"name": "Бразильский орех", "product_type": "other", "calories": 659, "fats": 67.1, "proteins": 14.3, "carbs": 12.3},
    {"name": "Кедровый орех", "product_type": "other", "calories": 689, "fats": 68.4, "proteins": 13.7, "carbs": 13.1},
    {"name": "Пекан", "product_type": "other", "calories": 691, "fats": 72.0, "proteins": 9.2, "carbs": 13.9},
    {"name": "Семена тыквы", "product_type": "other", "calories": 559, "fats": 49.0, "proteins": 30.2, "carbs": 10.7},
    {"name": "Кокосовая стружка", "product_type": "other", "calories": 601, "fats": 65.0, "proteins": 13.0, "carbs": 14.0},
    {"name": "Арахисовая паста", "description": "Указаны значения для натуральной пасты без добавления сахара и масел", "product_type": "other", "calories": 588, "fats": 50.0, "proteins": 25.0, "carbs": 20.0},
    {"name": "Сахар", "product_type": "other", "calories": 398, "fats": 0.0, "proteins": 0.0, "carbs": 99.7},
    {"name": "Фруктоза", "product_type": "other", "calories": 399, "fats": 0.0, "proteins": 0.0, "carbs": 99.8},
    {"name": "Сироп агавы", "product_type": "other", "calories": 310, "fats": 0.0, "proteins": 0.0, "carbs": 76.0},
    {"name": "Кленовый сироп", "product_type": "other", "calories": 260, "fats": 0.1, "proteins": 0.0, "carbs": 67.0},
    {"name": "Варенье малиновое", "product_type": "other", "calories": 273, "fats": 0.0, "proteins": 0.6, "carbs": 70.4},
    {"name": "Джем клубничный", "product_type": "other", "calories": 271, "fats": 0.0, "proteins": 0.3, "carbs": 68.0},
    {"name": "Кетчуп", "product_type": "other", "calories": 93, "fats": 0.0, "proteins": 1.8, "carbs": 22.2},
    {"name": "Майонез Провансаль", "product_type": "other", "calories": 624, "fats": 67.0, "proteins": 3.1, "carbs": 2.6},
    {"name": "Майонез легкий", "product_type": "other", "calories": 260, "fats": 25.0, "proteins": 0.5, "carbs": 7.5},
    {"name": "Горчица", "product_type": "other", "calories": 162, "fats": 11.1, "proteins": 9.9, "carbs": 5.3},
    {"name": "Соевый соус", "product_type": "other", "calories": 53, "fats": 0.0, "proteins": 6.0, "carbs": 7.0},
    {"name": "Уксус яблочный", "product_type": "other", "calories": 21, "fats": 0.0, "proteins": 0.0, "carbs": 0.9},
    {"name": "Уксус бальзамический", "product_type": "other", "calories": 88, "fats": 0.0, "proteins": 0.5, "carbs": 17.0},
    {"name": "Масло подсолнечное", "product_type": "other", "calories": 899, "fats": 99.9, "proteins": 0.0, "carbs": 0.0},
    {"name": "Масло топленое (гхи)", "product_type": "other", "calories": 892, "fats": 99.0, "proteins": 0.2, "carbs": 0.0},
    {"name": "Масло льняное", "product_type": "other", "calories": 898, "fats": 99.8, "proteins": 0.0, "carbs": 0.0},
    {"name": "Масло кокосовое", "product_type": "other", "calories": 862, "fats": 100.0, "proteins": 0.0, "carbs": 0.0},
    {"name": "Масло кунжутное", "product_type": "other", "calories": 899, "fats": 99.9, "proteins": 0.0, "carbs": 0.0},
    {"name": "Тофу", "product_type": "other", "calories": 76, "fats": 4.8, "proteins": 8.1, "carbs": 1.9},
    {"name": "Соевое мясо", "product_type": "other", "calories": 296, "fats": 2.0, "proteins": 52.0, "carbs": 17.0},
    {"name": "Желатин", "product_type": "other", "calories": 355, "fats": 0.4, "proteins": 87.2, "carbs": 0.7},
    {"name": "Кофе черный без сахара", "product_type": "beverages", "calories": 2, "fats": 0.0, "proteins": 0.2, "carbs": 0.3},
    {"name": "Капучино", "product_type": "beverages", "calories": 40, "fats": 2.0, "proteins": 2.0, "carbs": 3.5},
    {"name": "Латте", "product_type": "beverages", "calories": 50, "fats": 2.5, "proteins": 2.5, "carbs": 4.0},
    {"name": "Американо", "product_type": "beverages", "calories": 2, "fats": 0.0, "proteins": 0.2, "carbs": 0.3},
    {"name": "Эспрессо", "product_type": "beverages", "calories": 9, "fats": 0.2, "proteins": 0.1, "carbs": 1.7},
    {"name": "Кола", "description": "Усредненные КБЖУ, могут немного отличаться в зависимости от производителя", "product_type": "beverages", "calories": 42, "fats": 0.0, "proteins": 0.0, "carbs": 10.6},
    {"name": "Кола Zero", "product_type": "beverages", "calories": 0, "fats": 0.0, "proteins": 0.0, "carbs": 0.0},
    {"name": "Энергетик", "product_type": "beverages", "calories": 45, "fats": 0.0, "proteins": 0.4, "carbs": 11.3},
    {"name": "Чай пуэр (заваренный)", "product_type": "beverages", "calories": 2, "fats": 0.0, "proteins": 0.2, "carbs": 0.4},
    {"name": "Чай улун (заваренный)", "product_type": "beverages", "calories": 1, "fats": 0.0, "proteins": 0.1, "carbs": 0.2},
    {"name": "Чай ромашковый", "product_type": "beverages", "calories": 1, "fats": 0.0, "proteins": 0.0, "carbs": 0.2},
    {"name": "Матча (сухой порошок)", "product_type": "beverages", "calories": 315, "fats": 5.0, "proteins": 30.0, "carbs": 38.0},
    {"name": "Стевия (порошок)", "description": "Натуральный сахарозаменитель", "product_type": "other", "calories": 0, "fats": 0.0, "proteins": 0.0, "carbs": 0.0},
    {"name": "Сорбит", "description": "Сахарный спирт, калорийный заменитель", "product_type": "other", "calories": 354, "fats": 0.0, "proteins": 0.0, "carbs": 94.5},
    {"name": "Ксилит", "description": "Сахарный спирт, менее калорийный чем сахар", "product_type": "other", "calories": 240, "fats": 0.0, "proteins": 0.0, "carbs": 100.0},
    {"name": "Суп Фо Бо", "description": "Усредненно на 100 мл. Говяжий бульон, рисовая лапша, тонко нарезанная говядина, ростки сои, зелень.", "product_type": "other", "calories": 52, "fats": 1.5, "proteins": 4.0, "carbs": 5.5},
    {"name": "Суп Куриный с лапшой", "description": "Усредненно на 100 мл. Куриный бульон, филе грудки, яичная лапша, морковь, лук.", "product_type": "other", "calories": 45, "fats": 1.2, "proteins": 3.5, "carbs": 4.8},
    {"name": "Борщ с говядиной", "description": "Усредненно на 100 мл. На мясном бульоне с говядиной, капустой, свеклой, картофелем.", "product_type": "other", "calories": 48, "fats": 2.2, "proteins": 3.2, "carbs": 4.5},
    {"name": "Суп Том Ям", "description": "Усредненно на 100 мл. Тайский суп на кокосовом молоке с креветками, пастой и грибами.", "product_type": "other", "calories": 85, "fats": 5.5, "proteins": 4.5, "carbs": 4.0},
)

def seedbase(db: Session) -> None:
    for pr in baseprods:
        ex = db.scalar(select(baseprod).where(baseprod.name == pr["name"]))
        if ex is None:
            db.add(baseprod(**pr))
        else:
            for k, v in pr.items():
                setattr(ex, k, v)
    db.commit()


